#!/usr/bin/env bash

# Bind search string to first argument.
if [ -z "$1" ]; then
  echo "Please enter a search string."
  exit 1
elif [ ! -z "$2" ]; then
  echo "Look's like you have more than one word in your search. If you're attempting to search a phrase, please wrap your search in quotation marks."
  exit 1
else
  SEARCH_STRING="$1"
  SEARCH_STRING=${SEARCH_STRING// /+}
fi

# Describe desired results.
RESULT_SCHEMA="{
    Word: .word,
    Def: .definition,
    Ayys: .thumbs_up,
    Nayys: .thumbs_down
  }"

# Bind results object to API response object as Array.
RESULTS_OBJ=$(curl -sS "http://api.urbandictionary.com/v0/define?term=$SEARCH_STRING" | jq '.list')

# Print the first three results.
echo "$RESULTS_OBJ" | jq ".[0] | $RESULT_SCHEMA"
echo "$RESULTS_OBJ" | jq ".[1] | $RESULT_SCHEMA"
echo "$RESULTS_OBJ" | jq ".[2] | $RESULT_SCHEMA"
